### DISCUSSION TITLE
Is it possible to run fake-gcs-server without root privileges?

### DISCUSSION THREAD

**Discussion by ViliusS** [fsouza/fake-gcs-server#1397] [Q&A] [answered]
I tried to run fake-gcs-server docker image with Kubernetes options below, but as soon the container starts it says that it is unable to `mkdir /storage/`

Is it possible to run the image without root privileges?

```
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
```
