### ISSUE TITLE
CORS Allow origin

### ISSUE THREAD

**Issue by Nicobas** [fsouza/fake-gcs-server#1117]
Hi!

My api I generate signed links for download/upload files. When I use these links from my front-end in Vue.js I get CORS errors telling me that the origin is not the right one. fake-gcp-storage is running with docker on localhost:8001 and my front-end on localhost:1234. In the code of this project there seems to be an "Access-Control-Allow-Origin: *" rule but it doesn't work. How can I authorize my front end to acces to these ressources?

This is my docker compose config :
```
  storage:
    container_name: b4m-storage
    image: fsouza/fake-gcs-server:1.44
    volumes:
      - ./.tmp/storage_data:/storage
    ports:
      - "8081:8081"
    command: ["-scheme", "http", "-port", "8081", "-external-url", "http://localhost:8081", '-public-host', "localhost:8081"]
```

Thanks
