### ISSUE TITLE
Object 404 when using Google Go client

### ISSUE THREAD

**Issue by Schachte** [fsouza/fake-gcs-server#1342]
I have the option for enabling custom endpoint during initialization in the Google go client:

```go
	if cfg.CustomEndpoint != "" {
		clientOpts = append(clientOpts, option.WithEndpoint(cfg.CustomEndpoint))
	}
```

and configure like the following:

```yaml
  fake-gcs-server:
    image: fsouza/fake-gcs-server
    ports:
      - "4443:4443"
    command:
    - '-scheme'
    - 'http'
    - '-port'
    - '4443'
    - '-public-host'
    - 'fake-gcs-server:4443'
    - '-external-url'
    - 'http://fake-gcs-server:4443'
    volumes:
      - ./fixtures/sample_videos:/data/my-cool-bucket
      - ./scripts/gcs_config.json:/data/config.json
```

I've manipulated the public-host and external-url params, but still just get a 404 on my objects. My current ENV for the hostname is set as :

```
GCS_CUSTOM_ENDPOINT=http://fake-gcs-server:4443/storage/v1
```

If I curl locally outside my test, I can see the data, but not while using the go client. Any ideas what could be going on here?
