### ISSUE TITLE
Unable to upload file to bucket: getting 404

### ISSUE THREAD

**Issue by mswami1** [fsouza/fake-gcs-server#1753]
Error:

Writer.Close: googleapi: Error 404: Not Found, Not Found

docker service:

 storage:
    image: fsouza/fake-gcs-server
    environment:
      STORAGE_EMULATOR_HOST: localhost:4443
    ports:
      - '4443:4443'
    command: -scheme http -port 4443 -public-host localhost:4443
    volumes:
      - .:/gcs_storage
      
   client, err1 := storage.NewClient(context.TODO(), option.WithEndpoint("http://127.0.0.1:4443/storage/v1/"))

**Comment by KeithScheiwiller** [comment]
Did you create a directory within `/storage` with the matching bucket name? I faced the same issue but doing so solved it. I didn't see it mentioned in the docs, but it seems it does not auto-create buckets.

**Comment by fsouza** [comment]
Yeah upload will fail if the bucket doesn't exist. I'll keep this open to improve the error message or at least log that the bucket doesn't exist.

**Comment by daaain** [comment]
To answer my own question, `/data` is what supposed to be a volume and `/storage` is the internal backend where `*.bucketMetadata` files get created, so if you you have a volume attached to `/storage` you'll get one level deeper `*.bucketMetadata.bucketMetadata` on every restart 😅 

Also, attaching a subdirectory to `/data` does make the emulator treat it as an existing bucket.

Would be really helpful if this was documented!

So I can upload to the bucket using the [gsutil example](https://github.com/fsouza/fake-gcs-server/blob/main/examples/gsutil/gsutil-example.sh), but I still get 404 when trying to use a signed URL generated by the Node SDK 🤷 the container logs it so the request gets through, it just returns 404

**Comment by daaain** [comment]
Got it working! Apparently it was a `public-host` mismatch, with this configuration the PUT signed URL did upload:

```yaml
services:
  fake-gcs:
    container_name: fake-gcs
    image: fsouza/fake-gcs-server:latest
    command: -scheme both -cors-headers x-goog-content-length-range,content-length -public-host 127.0.0.1:8000
    ports:
      - "127.0.0.1:9023:4443"
      - "127.0.0.1:8000:8000"
    volumes:
      - ${PWD}/.docker/gcs-emulator:/data
  app:
    ...
    environment:
      STORAGE_EMULATOR_HOST: http://127.0.0.1:8000
```
