### ISSUE TITLE
Pubsub Integration Sanity Check

### ISSUE THREAD

**Issue by ihandley-efx** [fsouza/fake-gcs-server#1898]
Can someone please verify `fake-gcs-server` still publishes notification messages to a pubsub emulator? 

I've scoured this repo looking for information:
- I followed the thread discussion with @Ortega-Dan ([see](https://github.com/fsouza/fake-gcs-server/pull/490#issuecomment-1546489345))
- I followed the thread started by @rogierlommers ([see](https://github.com/fsouza/fake-gcs-server/issues/24#issue-426691652))
- I looked over the [notification module](https://github.com/fsouza/fake-gcs-server/tree/main/internal/notification)

I just can't get `fake-gcs-server` to publish a message.

I'm doing this in Docker; here is the relevant portion of my `docker-compose.yml`:
```
storage:
    image: fsouza/fake-gcs-server:latest
    depends_on:
      pubsub-init:
        condition: service_completed_successfully
    volumes:
      - ./integration_tests/cloudstorage/:/data
    environment:
      PUBSUB_EMULATOR_HOST: localhost:8085
    ports:
      - '0.0.0.0:9023:9023'
    command: >
      -data=/data
      -scheme=http
      -port=9023
      -event.pubsub-project-id=test-project
      -event.pubsub-topic=test-topic
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:9023/_internal/healthcheck
        || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    platform: linux/amd64

  pubsub:
    image: us-docker.pkg.dev/iaas-gcr-reg-prd-ad3d/build/google/google-toolbox-emulator:1.0
    environment:
      GCP_PROJECT_ID: test-project
    ports:
      - '0.0.0.0:8085:8085'
    command: >
      bash -c '
        gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project=$$GCP_PROJECT_ID
      '
    healthcheck:
      test: curl --fail http://localhost:8085/
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 10s
    platform: linux/amd64

  pubsub-init:
    image: us-docker.pkg.dev/iaas-gcr-reg-prd-ad3d/build/google/google-toolbox-emulator:1.0
    depends_on:
      pubsub:
        condition: service_healthy
    environment:
      GCP_PROJECT_ID: test-project
      GCP_PUBSUB_SUBSCRIPTION_ID: test-subscription
      GCP_PUBSUB_TOPIC_ID: test-topic
      PUBSUB_EMULATOR_HOST: pubsub:8085
    command: >
      bash -c '
        curl -f -H "Content-Type: application/json" -X PUT "http://$$PUBSUB_EMULATOR_HOST/v1/projects/$$GCP_PROJECT_ID/topics/$$GCP_PUBSUB_TOPIC_ID"
        curl -f -H "Content-Type: application/json" -X PUT -d "{
            \"topic\": \"projects/$$GCP_PROJECT_ID/topics/$$GCP_PUBSUB_TOPIC_ID\"
        }" "http://$$PUBSUB_EMULATOR_HOST/v1/projects/$$GCP_PROJECT_ID/subscriptions/$$GCP_PUBSUB_SUBSCRIPTION_ID"
      '
    platform: linux/amd64

``` 
The test I'm running writes an object to the `fake-gcs-server`'s bucket, and it seems to be doing that as seen here in the logs:

```
2025-02-13 06:57:31 storage-1      | time=2025-02-13T13:57:31.096Z level=INFO msg="172.20.0.1 - - [13/Feb/2025:13:57:31 +0000] \"POST /upload/storage/v1/b/test-bucket/o?alt=json&name=test-rdr-file.csv&prettyPrint=false&projection=full&uploadType=multipart HTTP/1.1\" 200 823\n"
2025-02-13 06:57:34 storage-1      | time=2025-02-13T13:57:34.747Z level=INFO msg="::1 - - [13/Feb/2025:13:57:34 +0000] \"GET /_internal/healthcheck HTTP/1.1\" 200 0\n"
``` 

I don't see any log message(s) written to indicate a message has been published nor has my pubsub listener picked anything up.

Any ideas what I'm missing here? Thanks in advance!
