### ISSUE TITLE
Getting "certificate is valid for example.com, not localhost"

### ISSUE THREAD

**Issue by anasanzari** [fsouza/fake-gcs-server#459]
Getting this error "certificate is valid for example.com, not localhost" with go client

compose file
```
version: "3"
services:
    image: fsouza/fake-gcs-server
    ports:
      - 4443:4443
```

go code:

```
client, err := storage.NewClient(context.Background(), opt, option.WithEndpoint("https://localhost:4443/storage/v1/"))
acl := s.Storage.Bucket(BucketName).Object(fileName).ACL()
if err := acl.Set(ctx, storage.AllUsers, storage.RoleReader); err != nil {
	return err
}
```
