### ISSUE TITLE
qemu segmentation fault on Apple M1 / arm64

### ISSUE THREAD

**Issue by markerdmann** [fsouza/fake-gcs-server#580]
The container crashes immediately after startup on an M1 Macbook. This is the log output:

fakegcs_1           | time="2021-09-23T18:41:16Z" level=info msg="server started at https://[::]:4443"
fakegcs_1           | qemu: uncaught target signal 11 (Segmentation fault) - core dumped

**Comment by fsouza** [comment]
@markerdmann thanks for reporting. I don't have an M1 currently, so hard for me to investigate this 😞 

Are you able to reproduce it when running natively, without a container?

**Comment by markerdmann** [comment]
My current workaround is just to clone this repo and run with the fake-gcs-server/Dockerfile.

This might be the solution? https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by fsouza** [comment]
Oh I see, is the problem only when you pull the image from Docker Hub? I'll investigate more later.

**Comment by markerdmann** [comment]
Yes, I think when building locally, Docker is able to use the multiarch builds of the two base images referenced in the Dockerfile.

**Comment by stoffeastrom** [comment]
@fsouza  Looks like you are using github actions. There are some actions available. 

https://github.com/docker/setup-buildx-action#with-qemu

Something like: (*note* haven't tested this myself yet)

```yaml
name: docker-push
on: create

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        if: github.event.ref_type == 'tag'

      - uses: actions/setup-go@v2.1.5
        if: github.event.ref_type == 'tag'
        id: go
        with:
          go-version: 1.17

      - name: go-build
        if: github.event.ref_type == 'tag'
        run: go build -o fake-gcs-server
        env:
          CGO_ENABLED: 0

      - name: sanity-check
        if: github.event.ref_type == 'tag'
        uses: docker://alpine
        with:
          entrypoint: sh
          args: -c "./fake-gcs-server -h"

      - name: docker-publish
        if: github.event.ref_type == 'tag'
        uses: fsouza/docker-publish-action@v1.0.1
        with:
          dockerfile: ci/Dockerfile
          docker-image: fsouza/fake-gcs-server
          DOCKER-USERNAME: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}

      - name: setup qemu
        if: github.event.ref_type == 'tag'
        uses: docker/setup-qemu-action@v1
      - name: setup buildx
        if: github.event.ref_type == 'tag'
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: available platforms
        if: github.event.ref_type == 'tag'
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: login to docker hub
        if: github.event.ref_type == 'tag'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build the image
        if: github.event.ref_type == 'tag'
        run: |
          docker buildx build \
          --push \
          --tag ${{ secrets.DOCKER_USERNAME }}/fake-gcs-server:latest \
          --platform linux/amd64,linux/arm64 .
```
