### ISSUE TITLE
Add an example to run the image in .gitlab-ci.yml

### ISSUE THREAD

**Issue by sorasful** [fsouza/fake-gcs-server#619]
Hello,

As I'm starting to use fake-gcs-server for one of my project, I'm trying to setup a service in my .gitlab-ci.yml file. So far I have some troubles to set it up. But once I figure it out, what would you think about adding a section in the documentation to show the configuration to be able to run it in Gitlab-CI ?

**Comment by fsouza** [comment]
@sorasful hey, yeah we could add that to the documentation x)

Let me know if I can help in any way.

**Comment by sorasful** [comment]
@fsouza  Yeah, I think that a lot of people use this for their projects in their CI, I'm personnally using Gitlab-ci so I thought this would be a good idea. Could be great for other platforms too, but let's open an issue when that will be needed.

Also, I didn't manage to make it work yet, I have some troubles with : 

```
Health check container logs:
2021-11-10T19:27:58.202405563Z [31;1mFATAL: No HOST or PORT found           
```

And my Gitlab-ci looks like this : 

```yml
image: python:3.9

services:
  - name: fsouza/fake-gcs-server
    alias: gcloud-emulator

variables:
  STORAGE_EMULATOR_HOST: gcloud-emulator:4443

... rest of the file
```

**Comment by sorasful** [comment]
Okay, so despite the warning saying `No HOST or PORT found` it seems that the service starts well and is working. Now just need to find out how to add volumes.

**Comment by matthewbal** [comment]
I'm also trying to get this to work, I'll post my gitlab-ci when I manage to get it connecting properly.

**Comment by matthewbal** [comment]
We have a FastAPI project, using the async google cloud storage library gcloud.aio.storage.
This is what I had to do:

in gitlab-ci.yml

```
pytest-job:
  services:
    - name: fsouza/fake-gcs-server
      command: ["-scheme", "http"]
  stage: test
  script:
    - echo "Your test script"
```


Then, when you want to connect to the container, you need to reference the hostname like this (gitlab by default maps service names to hostnames and replaces / with -)

```
BUCKET_EMULATOR_URL: str = (
    "http://fsouza-fake-gcs-server:4443"
)
```

You can't use volumes in gitlab, so there's no easy way to create your bucket and test files, so I used a pytest autouse fixture to do that.

```
@pytest.fixture(scope="session", autouse=True)
async def add_test_txt_to_test_bucket():
    """
    Guarentees that we have test.txt uploaded so we can easily test it in gitlab
    """
    async with Session() as session:
        storage = Storage(
            service_file=settings.GCP_BUCKET_CREDS_LOCATION,
            session=session,
            api_root=settings.BUCKET_EMULATOR_URL,
        )

        test_bucket_config = {
            "name": "fake-bucket",
            "location": "US-CENTRAL1",
            "storageClass": "NEARLINE",
            "iamConfiguration": {
                "uniformBucketLevelAccess": {"enabled": True},
            },
        }

        async with AsyncClient() as client:
            await client.post(url=f"{settings.BUCKET_EMULATOR_URL}/storage/v1/b", json=test_bucket_config)

        await storage.upload(
            bucket="fake-bucket",
            object_name="test.txt",
            file_data="This file is served from our fake-bucket locally",
        )

```

Now from tests we are able to connect to the bucket `fake-bucket`, and the file `test.txt` is already loaded onto it.
Locally, if you use docker compose, you would need to connect with `http://localhost:4443` from outside the docker stack, but from within the docker stack you can also use `http://fsouza-fake-gcs-server:4443` as long as you set the service name up that way.

Here's a docker-compose for completeness:

```
services:
  api_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code/ # ALL config files get loaded into the container
    ports:
      - 9090:8080
    env_file:
      - .docker-api.env
    depends_on:
      - postgres
      - fsouza-fake-gcs-server
  fsouza-fake-gcs-server:
    image: fsouza/fake-gcs-server
    ports:
      - 4443:4443
    command: -scheme http
```

Hope this helps someone!
