### ISSUE TITLE
Failed to get object with error `storage: object doesn't exist` @ `1.37.0`

### ISSUE THREAD

**Issue by chunming-c** [fsouza/fake-gcs-server#713]
Hi, thank you for the work. However, when upgrade to `v1.37.0`, `object` was failed to be retrieved by gcs client. The tricky part is the object does exist and accessible by `curl`.

```
curl -I --insecure https://0.0.0.0:4443/storage/v1/b/foo/o/bar.txt | jq .

{
  "kind": "storage#object",
  ...
}
```

```go
func setup() (gcsClient *storage.Client) {
	transCfg := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	httpClient := &http.Client{Transport: transCfg}
	gcsClient, _ = storage.NewClient(
		context.TODO(),
		option.WithEndpoint("https://localhost:4443/storage/v1/"),
		option.WithHTTPClient(httpClient),
	)
	return
}

func main() {
	gcsClient := setup()
	obj := gcsClient.Bucket("foo").Object("bar.txt").ReadCompressed(true)

	_, err := obj.NewReader(context.Background())
	if err != nil {
		log.Fatal(err.Error()) // storage: object doesn't exist
	}
}
```

### Version

- cloud.google.com/go/storage:  v1.16.0
- fake-gcs-server: 1.37.0

**Comment by fsouza** [comment]
Hi @chunming-c, can you share how you started the server? Like which arguments you provided to it.

**Comment by chunming-c** [comment]
Yeah sure. The server is started by docker compose with config below
```yml
version: '3.9'
services:
    fake-gcs-server:
        container_name: fake-gcs-server
        image: fsouza/fake-gcs-server:1.37.0
        ports:
            - 4443:4443
        volumes:
            - ../../test/gcs_test_bucket:/data/foo
        entrypoint: ['/bin/fake-gcs-server', '-data', '/data', '-public-host', 'localhost']
```
