### ISSUE TITLE
Sharing volume on macOS: "failed to determine if storage supports xattr"

### ISSUE THREAD

**Issue by tdeg** [fsouza/fake-gcs-server#894]
Hi. I am trying to mount a volume between my host machine and docker container. My goal is be able to see the data that is getting uploaded outputted to a folder in my project's directory. After reading through the codebase my current configuration looks like this:

```
services:
  my_service:
    build:
      context: "."
      dockerfile: dev.Dockerfile
    depends_on:
        - db
    volumes:
      - .:/myservice
      - ./storage:/storage
    environment:
      STORAGE_EMULATOR_HOST: http://storage:4443
    ports:
      - 8080:8080
    networks:
      - network

  storage:
    image: fsouza/fake-gcs-server
    volumes:
      - ./storage:/storage
    ports:
      - 4443:4443
    networks:
      - network
    command:
      - "-scheme" 
      - "http"
      - "-backend" 
      - "filesystem"
  networks:
    network:
```

When running compose up, the container crashes with the following error: 
```
level=fatal msg="couldn't start the server" error="failed to determine if \"/storage/\" supports xattr, consider using a different storage backend or a filesystem that supports it (e.g. not tmpfs on Linux): xattr.get /storage/ user.metadata: operation not supported"
```

If I remove the volume from the storage definition the container builds and I can access the buckets via cURL. Any help is greatly appreciated.
