### ISSUE TITLE
storage: object doesn't exist on object.Update

### ISSUE THREAD

**Issue by bzon** [fsouza/fake-gcs-server#936]
The example code works fine if using the real google cloud storage client.

Server Installation:

```yaml
version: '3.3'

volumes:
  gcs_test_bucket:
services:
  fake-gcs-server:
    image: fsouza/fake-gcs-server:1.40
    ports:
      - "4443:4443"
    expose:
      - "4443"
    volumes:
      - gcs_test_bucket:/data
    entrypoint: ["fake-gcs-server", "-backend=filesystem", "-data=/data", "-public-host=localhost:4443"]
```

Sample Code:

```go
package main

import (
	"context"
	"crypto/tls"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"

	"cloud.google.com/go/storage"
	"google.golang.org/api/iterator"
	"google.golang.org/api/option"
)

func main() {
	transCfg := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	httpClient := &http.Client{Transport: transCfg}
	client, err := storage.NewClient(context.TODO(), option.WithEndpoint("https://localhost:4443/storage/v1/"), option.WithHTTPClient(httpClient))
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	const (
		bucketName = "sample-bucket"
		fileKey    = "some_file.txt"
	)

	ctx := context.Background()
	bucket := client.Bucket(bucketName)

	// if err := bucket.Create(ctx, "project", nil); err != nil {
	// 	log.Println("create bucket failed:", err)
	// }

	os.Create(fileKey)

	f, err := os.Open(fileKey)
	if err != nil {
		log.Fatalf("failed to open/create file: %v", err)
	}

	object := bucket.Object(fileKey)
	wc := object.NewWriter(ctx)

	if _, err := io.Copy(wc, f); err != nil {
		log.Fatalf("failed to upload: %v", err)
	}

	if err := wc.Close(); err != nil {
		log.Fatalf("failed to upload: %v", err)
	}

	buckets, err := list(client, bucketName)
	if err != nil {
		log.Fatalf("failed to list: %v", err)
	}

	fmt.Printf("buckets: %+v\n", buckets)

	// try update object
	if _, err := object.Update(ctx, storage.ObjectAttrsToUpdate{Metadata: map[string]string{"k": "v"}}); err != nil {
		log.Fatalf("failed to update: %v", err)
	}
}

func list(client *storage.Client, bucketName string) ([]string, error) {
	var objects []string
	it := client.Bucket(bucketName).Objects(context.Background(), &storage.Query{})
	for {
		oattrs, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			return nil, err
		}
		objects = append(objects, oattrs.Name)
	}
	return objects, nil
}

```

Output:

```
buckets: [some_file.txt]
2022/09/29 20:30:46 failed to update: storage: object doesn't exist
exit status 1
```
